### ISSUE TITLE
Task List / Bug List:

### ISSUE THREAD

**Issue by Montuuh** [FeroXx07/Donkey-Kong#5]
- [x] Arreglar collider mario al interactuar con las escaleras

- [x] Limites de terreno para que no se caiga por los lados

- [x] Arreglar las tuercas para que se ponga un muro que no deje pasar sin saltar

- [x] Agregar animaciones en idle de la escalera para que se quede quieto si no llegan inputs

- [x] Hacer que solo desaparezca nuts cuando mario esta justo en el medio encima

- [x] Arreglar win animation a partir de la segunda vez

- [x] Añadir sprites DK y princesa
